

export const fakeData = [
    {
        _id: 1,
        actorLoginId: 'buyer@buyer.com',
        actorLoginMail: 'buyer@buyer.com',
        actorLoginPhone: '12345678901',
        actorLoginPassword: '123',
        actorDP: 'https://dp.profilepics.in/profile_pictures/arab-boys/arab-stylish-boys-pics-dp-for-whatsapp-facebook-18.jpg',
        actorBio: 'John Doe Buyer is a professional Company owner and a leader , location of company is UK. Add 1 cup of frozen peas along with the mussels, if you like. ',
        actorFirstName: 'John',
        actorLastName: 'Doe Buyer',
        actorRole: 'seller',
        actorLocation: 'New York',
        propertyPosted: [{
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        }, {
            _id: 1,
            ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
            ownerMongoId: '1',
            ownerName: 'John Doe Buyer',
            actorMail: 'buyer@buyer.com',
            actorPhone: '12345678901',
            propertyTitle: 'Beautiful House',
            propertyDescription: 'Beautiful House in New York',
            propertyPrice: '$1,000,000',
            propertyType: 'House',
            propertyBedrooms: '3',
            propertyBathrooms: '2',
            propertyArea: '1,000 sqft',
            propertyAddress: '123 Main Street',
            propertyCity: 'New York',
            propertyState: 'NY',
            propertyZip: '10001',
            propertyCountry: 'USA',
            propertyLat: '40.7128',
            propertyLng: '-74.0060',
            propertySold: false,
            propertyNewOwner: {},
            propertyPhotos: [
                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

                'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

            ],
            propertyAmenities: [
                'Wifi',
                'Cable TV',
                'Air Conditioning',
                'Kitchen',
                'Heating',
                'Washer',
                'Dryer',
                'Breakfast',
                'Laptop Friendly Workspace',
                'Smoking Allowed',
                'Pets Allowed',
                'Doorman',
            ],
            propertyReviews: [
                {
                    _id: 1,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
                {
                    _id: 2,
                    reviewAuthor: 'John Doe Buyer',
                    reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    reviewAuthorRating: '5',
                    reviewAuthorReview: 'This is a great place to stay!',
                    reviewAuthorDate: '2020-01-01',
                },
            ],
            propertyPayment: 'fullpayment',
            propertyPaymentMethod: 'Stripe',
            propertyBids: [
                {
                    _id: 1,
                    bidAuthor: 'John Doe Buyer',
                    bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
                    bidAuthorChat: [],
                },
            ],
        },],
        likedProperties: [],
        bids: [],
    },


];


export const propertyPosted = [{
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
}, {
    _id: 1,
    ownerDP: 'https://www.w3schools.com/howto/img_avatar.png',
    ownerMongoId: '1',
    ownerName: 'John Doe Buyer',
    actorMail: 'buyer@buyer.com',
    actorPhone: '12345678901',
    propertyTitle: 'Beautiful House',
    propertyDescription: 'Beautiful House in New York',
    propertyPrice: '$1,000,000',
    propertyType: 'House',
    propertyBedrooms: '3',
    propertyBathrooms: '2',
    propertyArea: '1,000 sqft',
    propertyAddress: '123 Main Street',
    propertyCity: 'New York',
    propertyState: 'NY',
    propertyZip: '10001',
    propertyCountry: 'USA',
    propertyLat: '40.7128',
    propertyLng: '-74.0060',
    propertySold: false,
    propertyNewOwner: {},
    propertyPhotos: [
        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

        'https://images.pexels.com/photos/186077/pexels-photo-186077.jpeg?cs=srgb&dl=pexels-binyamin-mellish-186077.jpg&fm=jpg',

    ],
    propertyAmenities: [
        'Wifi',
        'Cable TV',
        'Air Conditioning',
        'Kitchen',
        'Heating',
        'Washer',
        'Dryer',
        'Breakfast',
        'Laptop Friendly Workspace',
        'Smoking Allowed',
        'Pets Allowed',
        'Doorman',
    ],
    propertyReviews: [
        {
            _id: 1,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
        {
            _id: 2,
            reviewAuthor: 'John Doe Buyer',
            reviewAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            reviewAuthorRating: '5',
            reviewAuthorReview: 'This is a great place to stay!',
            reviewAuthorDate: '2020-01-01',
        },
    ],
    propertyPayment: 'fullpayment',
    propertyPaymentMethod: 'Stripe',
    propertyBids: [
        {
            _id: 1,
            bidAuthor: 'John Doe Buyer',
            bidAuthorDP: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/10/Zayn_Wiki_%28cropped%29.jpg/800px-Zayn_Wiki_%28cropped%29.jpg',
            bidAuthorChat: [],
        },
    ],
},];